language: node_js
node_js:
  - "10.2"
sudo: enabled
cache: npm
branches:
  only:
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get install jq
  - npm install -g mocha
  - ./scripts/setup-student-repo.sh

script:
  - ./scripts/generate-report.sh
  - ./scripts/publish-report.sh
